name: Testspace
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Function name'
        required: true
      payload:
        description: 'Function input-payload'
        required: true
      context:
        description: 'Function execution-context'
        required: true
jobs:
  setup:
    if: github.event.inputs.name == 'setup' 
    #if: ${{ github.event.inputs.name == github.job }}
    #if: ${{ github.job == 'gh_fixture' }}
    #if: ${{ github.event.inputs.name == env.GITHUB_JOB }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Inputs
        run: |
          echo job: "${{ github.job }}" 
          echo job.name: "${{ job.name }}" 
          echo function: "${{ github.event.inputs.name }}"
          echo payload: "${{ github.event.inputs.payload }}"
          echo context: "${{ github.event.inputs.payload }}"
